name: insight
description: "Insight: The app by the students, and for the students of Indian Institute of Science Education and Research, Mohali."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  riverpod_annotation: ^2.3.3
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
